In [1]:
!pip install wandb
!wandb login

     |████████████████████████████████| 1.7 MB 28.7 MB/s 
     |████████████████████████████████| 181 kB 67.5 MB/s 
     |████████████████████████████████| 144 kB 70.6 MB/s 
     |████████████████████████████████| 63 kB 1.6 MB/s 
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8806 sha256=a7b36b7cf886bb9699b8bdd8732bbc61a0671bafde11d2f599648d1799172c33
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
Successfully built pathtools
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [2]:
import torch

## Creating Tensors

In [3]:
# A Number Tensor
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# A Vector Tensor
t2 = torch.tensor([1., 2, 4, 6, 8])
t2

tensor([1., 2., 4., 6., 8.])

In [6]:
# A Matrix Tensor
t3 = torch.tensor([[2.0, 3, 4, 5], [4, 7, 2, 3], [5, 2, 4, 3]])
t3

tensor([[2., 3., 4., 5.],
        [4., 7., 2., 3.],
        [5., 2., 4., 3.]])

In [7]:
# A n-dimensional array Tensor
t4 = torch.tensor([[[1., 2, 5], 
                    [3, 9, 10]], 
                   
                   [[7, 4, 5],
                    [4, 5, 6]]])
t4

tensor([[[ 1.,  2.,  5.],
         [ 3.,  9., 10.]],

        [[ 7.,  4.,  5.],
         [ 4.,  5.,  6.]]])

## Getting the SHAPE of a tensor

The shape of a tensor shows the number of dimensions in a tensor and the length of each dimension.

A number tensor has zero dimensions - zero dimension, no length.

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 4., 6., 8.])


torch.Size([5])

In [10]:
print(t3)
t3.shape

tensor([[2., 3., 4., 5.],
        [4., 7., 2., 3.],
        [5., 2., 4., 3.]])


torch.Size([3, 4])

In [11]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  5.],
         [ 3.,  9., 10.]],

        [[ 7.,  4.,  5.],
         [ 4.,  5.,  6.]]])


torch.Size([2, 2, 3])

Note that it's not possible to create a tensor with an improper dimension. This will result in a ValueError. This is where a tensor varies from a list of lists.


*   Tensor entries will have the same datatype
*   The dimension of the tensor has to be uniform / proper.



In [12]:
t5 = torch.tensor([[1., 2, 4],
                   [7, 8],
                   [1, 8, 4]])
t5

ValueError: ignored

## Tensor Operations and Gradients

In [13]:
# Create some Tensors

x = torch.tensor(4.)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(4., requires_grad=True)
x, w, b

(tensor(4.), tensor(2., requires_grad=True), tensor(4., requires_grad=True))

In [14]:
# Arithemetic Operation
y = w*x + b
y

tensor(12., grad_fn=<AddBackward0>)

In [15]:
# Compute derivatives
# If we compute the derivative of y, y.backward(), the gradients are stored in 
# the .grad property of the corresponding tensor, for all the tensors 
# that have the requires_grad parameter set to True. Gradienst are only computed 
# for tensors with reqires_grad=True

y.backward()

In [16]:
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(4.)
dy/db: tensor(1.)


## Tensor Functions

In [17]:
# Create a Tensor with a fixed value for every element

t6 = torch.full((3, 4), 40.)
t6

tensor([[40., 40., 40., 40.],
        [40., 40., 40., 40.],
        [40., 40., 40., 40.]])

In [18]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 2.,  3.,  4.,  5.],
        [ 4.,  7.,  2.,  3.],
        [ 5.,  2.,  4.,  3.],
        [40., 40., 40., 40.],
        [40., 40., 40., 40.],
        [40., 40., 40., 40.]])

In [19]:
t8 = torch.sin(t7)
t8

tensor([[ 0.9093,  0.1411, -0.7568, -0.9589],
        [-0.7568,  0.6570,  0.9093,  0.1411],
        [-0.9589,  0.9093, -0.7568,  0.1411],
        [ 0.7451,  0.7451,  0.7451,  0.7451],
        [ 0.7451,  0.7451,  0.7451,  0.7451],
        [ 0.7451,  0.7451,  0.7451,  0.7451]])

In [20]:
t9 = t8.reshape((3, 4, 2))
t9

tensor([[[ 0.9093,  0.1411],
         [-0.7568, -0.9589],
         [-0.7568,  0.6570],
         [ 0.9093,  0.1411]],

        [[-0.9589,  0.9093],
         [-0.7568,  0.1411],
         [ 0.7451,  0.7451],
         [ 0.7451,  0.7451]],

        [[ 0.7451,  0.7451],
         [ 0.7451,  0.7451],
         [ 0.7451,  0.7451],
         [ 0.7451,  0.7451]]])

[Learn more about Tensor operations]( https://pytorch.org/docs/stable/torch.html )



## Interoperabilty with Numpy

In [21]:
import numpy as np

x = np.array([[2, 4],
              [4, 5.]])
x

array([[2., 4.],
       [4., 5.]])

In [22]:
y = torch.from_numpy(x)
y

tensor([[2., 4.],
        [4., 5.]], dtype=torch.float64)

In [23]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [24]:
z = y.numpy()
z

array([[2., 4.],
       [4., 5.]])

One might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

**Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.

**GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

In [25]:
!pip install jovian --upgrade --quiet
import jovian

     |████████████████████████████████| 68 kB 5.4 MB/s 
