# 5 PyTorch Tensor functions you should know!

PyTorch is a python library that makes it possible to implement machine learning algorithms. The functions listed below are some of the functions provided by the PyTorch 'torch' module for manipulating 'tensors'.

- torch.numel
- torch.reshape
- torch.squeeze
- torch.save
- torch.argmax

Before we begin, let's install and import PyTorch

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.numel

`torch.numel(_tensor_object_)`

The `torch.numel` function returns the total **number of elements** in a tensor. The tensor can be a vector, matrix or a multi-dimensional tensor.

In [2]:
# Example 1 - working
t1 = torch.tensor([[1, 7, 13], [13, 12, 4.]])
torch.numel(t1)

6

Tensor **t1** above was initialized with a size [2, 3]

When we used the `numel` function on t1, we get the total number of individual elements within the tensor. 

In [3]:
# Example 2 - working
t2 = torch.randn([50, 1, 100, 100])
torch.numel(t2)

500000

Tensor **t2** above has 50 * 1 * 100 * 100 = 50_000 elements

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

t3 = np.array([[1, 2], [1, 5]])
torch.numel(t3)

TypeError: ignored

`torch.numel` will only works on valid tensor objects alone

> `torch.numel` can be uselful to validate that a tensor e.g a vector has the required number of elements


---

Let's save our work using Jovian before continuing.

In [5]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 3.0 MB/s 


In [6]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 2 - torch.reshape

`torch.reshape(_tensor_object_, _new_shape_)`

`torch.reshape` returns a tensor with the same data as *tensor_object*, but with a different shape.

In [7]:
# Example 1 - working

t1 = torch.randn([100, 100])  # e.g a grayscale image with size 100 x 100 px
torch.reshape(t1, [1, 10000]) # linearize the images

tensor([[-0.4963, -0.3753, -1.1320,  ..., -0.9093,  1.0271, -1.3528]])

A single 100 by 100 grayscale image was reshaped to a column vector. The column vector contains the same data, the same number of elements, but a different shape.

In [8]:
# Example 2 - working


t2 = torch.randn([15, 100, 100])  # e.g 15 grayscale images with size 100 x 100 px
torch.reshape(t2, [15, 10000]) # linearize the images

tensor([[-1.5972, -0.7447, -0.0405,  ...,  0.2952,  1.3329,  1.1278],
        [-0.5670, -0.1988, -0.0094,  ...,  0.4389, -1.5930,  0.3673],
        [ 0.5784,  0.1749, -0.6315,  ...,  0.4606, -1.8155, -0.2761],
        ...,
        [ 1.1681, -0.5200, -0.9719,  ...,  1.0722,  0.1800,  1.8981],
        [ 3.4992, -0.6011, -0.3001,  ...,  1.2804,  0.7422,  0.0966],
        [ 0.4314,  0.6922, -0.7297,  ..., -1.0397,  0.2947, -0.4852]])

A tensor containing 15 grayscale images was reshaped to contain 15 vectors. Each vector is an image linearized.

The reshaping of the tensor starts from the last dimesion of the input tensor, putting them elements after element into the new tensor, also from the last dimension.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)

t3 = torch.randn([15, 100, 100])  # e.g 15 grayscale images with size 100 x 100 px
torch.reshape(t3, [100, 10000]) # linearize the images

RuntimeError: ignored

The number of elements in the source tensor must match the number of elements that will result from the shape passed to `torch.reshape`.



`torch.tensor` is useful to manipulate tensors when the shape of the input data to a model or function, is different from the shape we have it in

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 3 - torch.squeeze

`torch.squeeze(*tensor_object*)`

`torch.squeeze` returns a new tensor where all dimensions with 1 element in *tensor_object* has been removed.

In [10]:
# Example 1 - working

t1 = torch.randn([1, 1, 100, 100])
t1_squeezed = torch.squeeze(t1)
t1_squeezed.shape

torch.Size([100, 100])

After squeezing the tensor, the first two dimesions with one element each has been removed

In [11]:
# Example 2 - working

t2 = torch.randn([15, 1, 100, 100])
t2_squeezed = torch.squeeze(t2)
t2_squeezed.shape

torch.Size([15, 100, 100])

The dimensions to squeeze can be at any position in the source tensor's shape

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

t3 = np.array([1,1,1])
t3_squeezed = torch.squeeze(t3)
t3_squeezed.shape

TypeError: ignored

`torch.squeezed` only works with tensor objects

Use the `torch.squeeze` function when yo don't need a redundant dimension with one element in a tensor

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 4 - torch.save

`torch.save(*tensor_object*, *file_path*)`

This funtion writes a tensor to the specified *file_path*, so that it can be opened again later for further use.

In [13]:
# Example 1 - working

t1 = torch.randn([3, 100, 100])
torch.save(t1, "Tensor_1")

After saving the tensor `t1`, it is now written to our hard disk in the specified path, and can be reloaded into our program anytime.

In [14]:
# Example 2 - working

t2 = torch.randn([100, 100])
torch.save(t2, "Tensor_2.pt")

The tensor can be saved with the desireed file extension. In this case '.pt'.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
t3 = np.array([1, 2, 3])
torch.save(t3)

TypeError: ignored

A file path must be provided to `torch.save` to specify where the tensor should be written.

`torch.save` can be useful to save a model's parameters - weights, biases - after training. This makes it possible to open the model at a later time, initialize the model's parameters with the saved tensors, and perform predictions.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - torch.argmax

`torch.argmax(tensor_object, dim)`

This function returns the indices of the maximum values in a tensor across a given dimension.

In [23]:
# Example 1 - working

t1 = torch.randn(5,4)
print(t1)
torch.argmax(t1, 1)

tensor([[ 0.4081, -0.0540,  1.6608,  0.4723],
        [-0.3585, -1.1258, -0.2213,  1.1039],
        [-1.6837,  0.0070, -1.2884, -1.6410],
        [-0.3338,  0.4399, -1.0982,  0.1663],
        [ 2.2238,  0.3226,  1.5540, -0.6752]])


tensor([2, 3, 1, 1, 0])

`argmax` returns the indices of the maximum values along each row of the input tensor.

In [18]:
# Example 2 - working

t2 = torch.randn(3, 4)
print(t2)
torch.argmax(t2)

tensor([[ 0.8378,  0.8103,  0.6692,  1.2534],
        [-0.2543, -0.5729, -1.2799, -1.2210],
        [-0.8597,  2.2554,  1.1538, -0.1711]])


tensor(9)

If no dimension `dim` is given, the argmax of the flattened tensor of the input is returned.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)

t3 = torch.randn(3,3)
print(t3)
torch.argmax(t3, 2)

tensor([[-1.8122,  0.1032, -2.3275],
        [-1.4366,  2.2172, -0.3875],
        [-1.4760,  1.6481,  0.6869]])


IndexError: ignored

If a dimension is provided to `argmax`, a valid dimension of the input tensor should be provided.

`torch.argmax` is very useful for finding the index of the maximum element of a tensor. For example, `argmax` is used to determine the predicted class from the output of a classification model 

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

In this notebook, we have seen five important PyTorch tensor functions, and how they are used, when to use them, and how not to use them.

The following five tensor functions were considered:

- torch.numel
- torch.reshape
- torch.squeeze
- torch.save
- torch.argmax

When these functions are maximised they help to make the deep learning workflow more effective and clean!

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Tensor - Wikipedia: https://en.wikipedia.org/wiki/Tensor

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
